### ISSUE TITLE
the file org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by Nythan** [Yuuko-oh/Yuuko#4]
Hello 
The file "org.gradle.wrapper.GradleWrapperMain" is not on your repositories but I would like use it for run the code of your bot on my sever vps.

Can you give me the file please or upload it on the repositorie please.

Thanks,
Nythan

**Comment by BasketBandit** [comment]
If you open the project and built it with grade in something like intellij it should automatically retrieve it, else: https://services.gradle.org/distributions/gradle-6.3-bin.zip

**Comment by Nythan** [comment]
hello,
it's not the file gradle it lose it's the file main.java it isn't on your repositorie.
can you give me this file please.
Thanks,
Nythan
